const projects = [
 {id:'electric-machine-cooling',number:'01',label:'HEAT TRANSFER / MULTIPHASE',title:'Electric-machine oil cooling',teaser:'Explaining how oil distribution changes thermal performance.',tags:'VOF · DPM · CHT<br>Rotating flow · HPC',question:'How does oil reach the cooling surfaces, and why can reversing rotation change the measured winding temperatures?',contribution:'Developed and executed stages of a team-based multiphysics methodology for rotating-shaft flow, jet breakup, droplet impingement and thermal analysis.',method:'Separated the short fluid-dynamic time scales from the longer thermal response. Transferred impingement information between modelling stages and examined local wetting, heat flux and heat transfer coefficients.',outcome:'The simulations helped explain the forward/reverse temperature difference observed in testing and identified non-uniform cooling. Local thermal results supported evaluation of the oil-delivery design.'},
 {id:'vehicle-airflow',number:'02',label:'AERODYNAMICS / THERMAL SYSTEMS',title:'Vehicle airflow and cooling',teaser:'Radiator airflow inputs for thermal-system calculations.',tags:'RANS · Porous media<br>Fan models · Test correlation',question:'Can a fuel-cell vehicle’s radiator arrangement provide the required cooling airflow across its operating envelope?',contribution:'Developed and executed the full-vehicle external-airflow and underhood CFD workflow, from complex geometry preparation through meshing and post-processing.',method:'Represented radiator resistance using porous media and fan behaviour using pressure-jump models. Compared operating speeds, fan states and selected obstruction scenarios; compared pressure predictions with Pitot measurements.',outcome:'Delivered radiator airflow inputs for the 1D thermal-system team and identified operating conditions where fan assistance was important. Calculated drag as an additional aerodynamic output; this case does not claim drag reduction.'},
 {id:'degassing',number:'03',label:'MULTIPHASE / PRODUCT DEVELOPMENT',title:'Gas separation in a coolant module',teaser:'Evaluating separation performance alongside hydraulic losses.',tags:'Gas–liquid flow · VOF<br>Design comparison · Physical testing',question:'How can an integrated cooling component separate entrained gas while maintaining acceptable hydraulic performance?',contribution:'Evaluated multiple geometries using multiphase CFD and communicated the trade-offs to the product-development team.',method:'Compared gas behaviour and separation mechanisms across design variants while considering pressure loss and packaging constraints.',outcome:'The selected concept was 3D-printed, physically tested and accepted for integration.'},
 {id:'condensation',number:'04',label:'PHASE CHANGE / METHOD DEVELOPMENT',title:'Modelling moisture and condensation',teaser:'Establishing a transient method before applying it to a component.',tags:'Species transport · Phase change<br>Transient thermal analysis',question:'How can moisture transport and condensation be represented in a thermal component over an extended cooling transient?',contribution:'Developed a transient CFD methodology and assessed it against published experimental benchmark data.',method:'Used the CONAN condensation benchmark to assess phase-change predictions, then studied numerical choices and a staged solution strategy to make longer physical times practical.',outcome:'The benchmark comparison showed a maximum deviation of about 4% under the tested conditions.'},
 {id:'valve-calibration',number:'05',label:'CFD / SYSTEM MODELLING',title:'CFD calibration of a 1D valve model',teaser:'Connecting viscous and inertial loss regimes to calibration.',tags:'Pressure loss · Python<br>Simcenter Amesim · Automation',question:'How can a reduced-order valve model represent pressure losses when temperature changes viscosity and the dominant flow regime?',contribution:'Developed a physics-based calibration workflow linking CFD operating points, Python automation and a Simcenter Amesim component model.',method:'Distinguished viscous and inertial contributions to pressure loss and calibrated the model across operating points rather than relying on a single nominal condition.',outcome:'Improved agreement across the evaluated operating envelope and created a repeatable calibration process. Detailed error metrics will be presented with their definitions, reference data and temperature ranges in the independent demonstration.'},
 {id:'flowpilot',number:'06',label:'SIMULATION AUTOMATION / OPENFOAM',title:'Hydraulic CFD workflow automation',teaser:'A graphical interface for repeated OpenFOAM studies.',tags:'OpenFOAM · Python · GUI<br>Workflow automation · HPC',question:'How can repeated hydraulic simulations be prepared and executed consistently without rebuilding the same workflow by hand?',contribution:'Developed FlowPilot, a Python-based graphical interface for an OpenFOAM hydraulic-simulation workflow.',method:'Organised repeated setup and execution tasks into a reusable workflow, applying CFD domain knowledge to the interface and automation.',outcome:'Created a tool for repeatable hydraulic analysis. A future independent walkthrough will demonstrate the public-safe workflow on a simplified geometry.'}
];

const highlights = {
 'electric-machine-cooling': {result:'Explained a thermal test anomaly',title:'Oil cooling in an electric machine',evidence:'Connected oil distribution to the temperature difference observed in forward/reverse testing.'},
 'vehicle-airflow': {result:'Built a ~100-million-cell vehicle model',title:'Vehicle airflow and radiator cooling',evidence:'Delivered radiator airflow data and compared pressure predictions with Pitot measurements.'},
 'degassing': {result:'Selected concept physically tested',title:'Gas separation in a coolant module',evidence:'The selected design was 3D-printed, tested and accepted for product integration.'},
 'condensation': {result:'~4% maximum benchmark deviation',title:'Condensation model and benchmark',evidence:'Compared phase-change predictions with the published CONAN experimental benchmark. The deviation applies to those benchmark conditions.'},
 'valve-calibration': {result:'A repeatable CFD-to-1D calibration',title:'CFD calibration of a 1D valve model',evidence:'Improved agreement over the evaluated operating envelope by separating viscous and inertial pressure-loss contributions.'},
 'flowpilot': {result:'Reusable hydraulic simulation workflow',title:'FlowPilot: OpenFOAM workflow automation',evidence:'Developed a Python graphical interface for a repeatable OpenFOAM hydraulic-simulation workflow.'}
};
const root = document.getElementById('projects');
for (const p of projects) {
 const h=highlights[p.id];
 const el=document.createElement('article');el.className='project-card';el.id=p.id;
 el.innerHTML=`<div class="card-top"><span class="project-label">${p.label}</span><span class="project-number">${p.number}</span></div><h3>${h.title}</h3><div class="result-block"><p class="result-label">ENGINEERING OUTCOME</p><strong>${h.result}</strong><p>${h.evidence}</p></div><div class="visible-case"><h4>The challenge</h4><p>${p.question}</p><h4>My contribution</h4><p>${p.contribution}</p></div><div class="card-bottom"><p class="project-tags">${p.tags.replace('<br>',' · ')}</p><details class="technical-detail"><summary>Modelling decisions <span aria-hidden="true">+</span></summary><div><p>${p.method}</p><h4>Scope &amp; outcome</h4><p>${p.outcome}</p></div></details><a class="case-link" href="#${p.id}" aria-label="Direct link to ${h.title}">Link to this case ↗</a></div>`;
 root.append(el);
}
function markLinkedCase(){document.querySelectorAll('.project-card').forEach(el=>el.classList.toggle('linked',el.id===location.hash.slice(1)));}
window.addEventListener('hashchange',markLinkedCase);markLinkedCase();
